{
  "allocateLike.options.prompt": "Select the profile to which the original data set belongs",
  "allocateLike.noSelection": "You must select a profile.",
  "allocateLike.inputBox.placeHolder": "Enter a name for the new data set",
  "allocateLike.noNewName": "You must enter a new data set name.",
  "createDataSet.log.error": "Error encountered when creating data set! ",
  "createDataSet.error": "Error encountered when creating data set! ",
  "enterPattern.pattern": "You must enter a pattern.",
  "deleteDatasetPrompt.nodesToDelete.empty": "Deleting data sets and members from the Favorites section is currently not supported.",
  "deleteDatasetPrompt.log.debug": "Deleting data set(s): ",
  "deleteDatasetPrompt.confirmation.delete": "Delete",
  "deleteDatasetPrompt.confirmation.message": "Are you sure you want to delete the following {0} item(s)?\nThis will permanently remove these data sets and/or members from your system.\n\n{1}",
  "deleteDatasetPrompt.deleteCancelled": "Delete action was cancelled.",
  "deleteDatasetPrompt.deleteCounter": "Deleting nodes",
  "deleteMulti.datasetNode": "The following {0} item(s) were deleted:{1}",
  "createMember.inputBox.placeholder": "Name of Member",
  "createMember.log.debug.createNewDataSet": "creating new data set member of name ",
  "createMember.log.error": "Error encountered when creating member! ",
  "createMember.error": "Unable to create member: ",
  "openPS.invalidNode": "openPS() called from invalid node.",
  "openPS.error.invalidNode": "openPS() called from invalid node. ",
  "openPS.log.debug.openDataSet": "opening physical sequential data set from label ",
  "openPS.log.error.openDataSet": "Error encountered when opening data set! ",
  "createFile.dataSetBinary": "Data Set Binary",
  "createFile.dataSetC": "Data Set C",
  "createFile.dataSetClassic": "Data Set Classic",
  "createFile.dataSetPartitioned": "Data Set Partitioned",
  "createFile.dataSetSequential": "Data Set Sequential",
  "createFile.quickPickOption.dataSetType": "Type of Data Set to be Created",
  "createFile.allocate": " + Allocate Data Set",
  "createFile.editAttributes": "Edit Attributes",
  "createFile.inputBox.placeHolder": "Name of Data Set",
  "createFile.noValidNameEntered": "No valid data set name entered. Operation cancelled",
  "createFile.operationCancelled": "Operation cancelled.",
  "createFile.noValidTypeSelected": "No valid data set type selected. Operation cancelled.",
  "createFile.noOptionSelected": "No option selected. Operation cancelled.",
  "createFile.allocatingNewDataSet": "Attempting to allocate new data set",
  "createFileNoWebview.options.prompt": "Click on parameters to change them",
  "showDSAttributes.debug": "showing attributes of data set ",
  "showDSAttributes.lengthError": "No matching data set names found for query: ",
  "showDSAttributes.log.error": "Error encountered when listing attributes! ",
  "showDSAttributes.error": "Unable to list attributes: ",
  "attributes.title": "Attributes",
  "submitJcl.noDocumentOpen": "No editor with a document that could be submitted as JCL is currently open.",
  "submitJcl.log.debug": "Submitting JCL in document ",
  "submitJcl.quickPickOption": "Select the Profile to use to submit the job",
  "submitJcl.noProfile": "No profiles available",
  "submitJcl.log.error.nullSession": "Session for submitting JCL was null or undefined!",
  "submitJcl.jobSubmitted": "Job submitted ",
  "submitJcl.jobSubmissionFailed": "Job submission failed\n",
  "submitJcl.checkProfile": "Profile is invalid",
  "submitMember.invalidNode": "submitMember() called from invalid node.",
  "submitMember.error.invalidNode": "submitMember() called from invalid node.",
  "submitMember.jobSubmitted": "Job submitted ",
  "submitMember.jobSubmissionFailed": "Job submission failed\n",
  "deleteDataSet.invalidNode.error": "deleteDataSet() called from invalid node.",
  "deleteDataSet.delete.log.error": "Error encountered when deleting data set! ",
  "deleteDataSet.error.notFound": "not found",
  "deleteDataSet.notFound.error1": "Unable to find file: ",
  "deleteDataSet.notFound.error2": " was probably already deleted.",
  "refreshPS.error.invalidNode": "refreshPS() called from invalid node.",
  "refreshPS.log.error.refresh": "Error encountered when refreshing data set view: ",
  "refreshPS.error.notFound": "not found",
  "refreshPS.file1": "Unable to find file: ",
  "refreshPS.file2": " was probably deleted.",
  "enterPattern.log.debug.prompt": "Prompting the user for a data set pattern",
  "enterPattern.inputBox.prompt": "Search Data Sets: use a comma to separate multiple patterns",
  "hMigrate.requestSent1": "Migration of dataset: ",
  "hMigrate.requestSent2": " requested.",
  "hMigrateDataSet.checkProfile": "Profile is invalid",
  "hRecall.requestSent1": "Recall of dataset: ",
  "hRecall.requestSent2": " requested.",
  "pasteMember.inputBox.placeHolder": "Name of Data Set Member",
  "saveFile.log.debug.request": "requested to save data set: ",
  "saveFile.log.debug.path": "path.relative returned a non-blank directory.",
  "saveFile.log.debug.directory": "Assuming we are not in the DS_DIR directory: ",
  "saveFile.log.error.session": "Couldn't locate session when saving data set!",
  "saveFile.log.debug.load": "Loading session from session node in saveFile()",
  "saveFile.log.debug.sessionNode": "couldn't find session node, loading profile with CLI profile manager",
  "saveFile.log.debug.saving": "Saving file ",
  "saveFile.error.saveFailed": "Data set failed to save. Data set may have been deleted on mainframe.",
  "saveFile.response.save.title": "Saving data set...",
  "saveFile.error.ZosmfEtagMismatchError": "Rest API failure with HTTP(S) status 412",
  "saveFile.error.etagMismatch": "Remote file has been modified in the meantime.\nSelect 'Compare' to resolve the conflict."
}
