{
    "enterPattern.pattern": "You must enter a pattern.",
    "createMember.inputBox": "Name of Member",
    "createMember.log.debug.createNewDataSet": "creating new data set member of name ",
    "createMember.log.error": "Error encountered when creating member! ",
    "createMember.error": "Unable to create member: ",
    "openPS.invalidNode": "openPS() called from invalid node.",
    "openPS.error.invalidNode": "openPS() called from invalid node. ",
    "openPS.log.debug.openDataSet": "opening physical sequential data set from label ",
    "openPS.log.error.openDataSet": "Error encountered when opening data set! ",
    "createFile.quickPickOption.dataSetType": "Type of Data Set to be Created",
    "createFile.dataSetBinary": "Data Set Binary",
    "createFile.dataSetC": "Data Set C",
    "createFile.dataSetClassic": "Data Set Classic",
    "createFile.dataSetPartitioned": "Data Set Partitioned",
    "createFile.dataSetSequential": "Data Set Sequential",
    "createFile.log.debug.noValidTypeSelected": "No valid data type selected",
    "createFile.log.debug.creatingNewDataSet": "Creating new data set",
    "dataset.name": "Name of Data Set",
    "createDataSet.error": "Error encountered when creating data set! ",
    "showDSAttributes.debug": "showing attributes of data set ",
    "showDSAttributes.lengthError": "No matching data set names found for query: ",
    "showDSAttributes.log.error": "Error encountered when listing attributes! ",
    "showDSAttributes.error": "Unable to list attributes: ",
    "attributes.title": "Attributes",
    "renameDataSet.log.debug": "Renaming data set ",
    "renameDataSet.log.error": "Error encountered when renaming data set! ",
    "renameDataSet.error": "Unable to rename data set: ",
    "submitJcl.noDocumentOpen": "No editor with a document that could be submitted as JCL is currently open.",
    "submitJcl.log.debug": "Submitting JCL in document ",
    "submitJcl.quickPickOption": "Select the Profile to use to submit the job",
    "submitJcl.noProfile": "No profiles available",
    "submitJcl.log.error.nullSession": "Session for submitting JCL was null or undefined!",
    "submitJcl.jobSubmitted": "Job submitted ",
    "submitJcl.jobSubmissionFailed": "Job submission failed\n",
    "submitMember.invalidNode": "submitMember() called from invalid node.",
    "submitMember.error.invalidNode": "submitMember() called from invalid node.",
    "submitMember.jobSubmitted": "Job submitted ",
    "submitMember.jobSubmissionFailed": "Job submission failed\n",
    "deleteDataset.log.debug": "Deleting data set ",
    "deleteDataset.quickPickOption": "Delete {0}? This will permanently remove it from your system.",
    "deleteDataset.showQuickPick.delete": "Delete",
    "deleteDataset.showQuickPick.Cancel": "Cancel",
    "deleteDataset.showQuickPick.log.debug": "User picked Cancel. Cancelling delete of data set",
    "deleteDataSet.invalidNode.error": "deleteDataSet() called from invalid node.",
    "deleteDataSet.delete.log.error": "Error encountered when deleting data set! ",
    "deleteDataSet.error.notFound": "not found",
    "deleteDataSet.notFound.error1": "Unable to find file: ",
    "deleteDataSet.notFound.error2": " was probably already deleted.",
    "refreshPS.error.invalidNode": "refreshPS() called from invalid node.",
    "refreshPS.log.error.refresh": "Error encountered when refreshing data set view: ",
    "refreshPS.error.notFound": "not found",
    "refreshPS.file1": "Unable to find file: ",
    "refreshPS.file2": " was probably deleted.",
    "enterPattern.log.debug.prompt": "Prompting the user for a data set pattern",
    "enterPattern.options.prompt": "Search data sets by entering patterns: use a comma to separate multiple patterns",
    "hMigrate.requestSent1": "Migration of dataset: ",
    "hMigrate.requestSent2": " requested.",
    "hRecall.requestSent1": "Recall of dataset: ",
    "hRecall.requestSent2": " requested.",
    "renameDataSet.name": "Name of Data Set Member",
    "saveFile.log.debug.request": "requested to save data set: ",
    "saveFile.log.debug.path": "path.relative returned a non-blank directory.",
    "saveFile.log.debug.directory": "Assuming we are not in the DS_DIR directory: ",
    "saveFile.log.error.session": "Couldn't locate session when saving data set!",
    "saveFile.log.debug.load": "Loading session from session node in saveFile()",
    "saveFile.log.debug.sessionNode": "couldn't find session node, loading profile with CLI profile manager",
    "saveFile.log.debug.saving": "Saving file ",
    "saveFile.error.saveFailed": "Data set failed to save. Data set may have been deleted on mainframe.",
    "saveFile.response.save.title": "Saving data set...",
    "saveFile.error.ZosmfEtagMismatchError": "Rest API failure with HTTP(S) status 412",
    "saveFile.error.etagMismatch": "Remote file has been modified in the meantime.\nSelect 'Compare' to resolve the conflict."
}